---
modules:
  chain_stats:
    body:
      content: |
        {"jsonrpc":"2.0","method":"taraxa_getChainStats","params":[],"id":1}
    metrics:
    - name: pbft_period
      path: '{ .result.pbft_period }'
      help: pbft_period from the mainnet dev rpc 
      labels:
        data_source: node_rpc
        rpc_method: taraxa_getChainStats

  rpc_node_status:
    body:
      content: |
        {"jsonrpc":"2.0","method":"get_node_status","params":[],"id":1}
    metrics:
    - name: rpc_node_status_dag_level
      path: '{ .result.dag_level }'
      labels: &rpc_node_status_labels
        data_source: node_rpc
        rpc_method: get_node_status
    - name: rpc_node_status_dpos_node_votes
      path: '{ .result.dpos_node_votes }'
      labels: *rpc_node_status_labels
    - name: rpc_node_status_dpos_quorum
      path: '{ .result.dpos_quorum }'
      labels: *rpc_node_status_labels
    - name: rpc_node_status_dpos_total_votes
      path: '{ .result.dpos_total_votes }'
      labels: *rpc_node_status_labels
    - name: rpc_node_status_network_peer_max_node
      path: '{ .result.network }'
      type: object
      values:
        dag_level: '{ .peer_max_node_dag_level }'
      labels:
        <<: *rpc_node_status_labels
        peer_max_node_dag_level_node_id: '{ .peer_max_node_dag_level_node_id }'
    - name: rpc_node_status_network_peer_max_pbft
      path: '{ .result.network }'
      type: object
      values:
        chain_size: '{ .peer_max_pbft_chain_size }'
      labels:
        <<: *rpc_node_status_labels
        peer_max_pbft_chain_size_node_id: '{ .peer_max_pbft_chain_size_node_id }'
    - name: rpc_node_status_network_peer_max_pbft_round
      path: '{ .result.network.peer_max_pbft_round }'
      labels: *rpc_node_status_labels
    - name: rpc_node_status_node_count
      path: '{ .result.node_count }'
      labels: *rpc_node_status_labels
    - name: rpc_node_status_pbft_round
      path: '{ .result.pbft_round }'
      labels: *rpc_node_status_labels
    - name: rpc_node_status_pbft_size
      path: '{ .result.pbft_size }'
      labels: *rpc_node_status_labels
    - name: rpc_node_status_pbft_sync_period
      path: '{ .result.pbft_sync_period }'
      labels: *rpc_node_status_labels
    - name: rpc_node_status_pbft_sync_queue_size
      path: '{ .result.pbft_sync_queue_size }'
      labels: *rpc_node_status_labels
    - name: rpc_node_status_peer_count
      path: '{ .result.peer_count }'
      labels: *rpc_node_status_labels
    - name: rpc_node_status_synced
      path: '{ .result.synced }'
      labels: *rpc_node_status_labels
    - name: rpc_node_status_syncing_seconds
      path: '{ .result.syncing_seconds }'
      labels: *rpc_node_status_labels
    - name: rpc_node_status_trx_count
      path: '{ .result.trx_count }'
      labels: *rpc_node_status_labels
    - name: rpc_node_status_trx_executed
      path: '{ .result.trx_executed }'
      labels: *rpc_node_status_labels
    - name: rpc_node_status_trx_nonfinalized_size
      path: '{ .result.trx_nonfinalized_size }'
      labels: *rpc_node_status_labels
    - name: rpc_node_status_trx_pool_size
      path: '{ .result.trx_pool_size }'
      labels: *rpc_node_status_labels

  node_stats:
    metrics:
    - name: indexer_stats_dags_count
      path: '{ .dagsCount }'
      help: DAG blocks produced by the node
      labels: &indexer_node_stats_labels
        data_source: indexer
    - name: indexer_stats_pbft_count
      path: '{ .pbftCount }'
      help: PBFT blocks produced by the node
      labels: *indexer_node_stats_labels
    - name: indexer_stats_last_dag_timestamp
      path: '{ .lastDagTimestamp }'
      help: Last DAG block timestamp
      labels: *indexer_node_stats_labels
    - name: indexer_stats_last_pbft_timestamp
      path: '{ .lastPbftTimestamp }'
      help: Last PBFT block timestamp
      labels: *indexer_node_stats_labels
