services:

  json_exporter:
    image: quay.io/prometheuscommunity/json-exporter
    volumes:
      - ./json_exporter/config.yml:/config.yml:ro
    ports:
      - 7979:7979

  prometheus:
    build: prometheus
    restart: unless-stopped
    entrypoint: ['/bin/entrypoint.sh']
    command: [ "--config.file=/etc/prometheus/prometheus.taraxa.yml", "--storage.tsdb.path=/prometheus" ]
    environment:
      - TARAXA_NODE_VALIDATORS
      - TARAXA_NODE_PROXY_AUTH_TYPE
      - TARAXA_NODE_PROXY_AUTH_CREDENTIALS
      - TARAXA_NODE_VALIDATORS_STATS_URL
    volumes:
      - ./prometheus/prometheus.yml.template:/etc/prometheus/prometheus.yml.template
      - prometheus_data:/prometheus
    #ports:
    #  - 9090:9090

  # https://grafana.com/docs/grafana/latest/setup-grafana/installation/docker/
  grafana:
    image: grafana/grafana-oss
    restart: unless-stopped    
    environment:
      - GF_SECURITY_ADMIN_PASSWORD
      - GF_USERS_ALLOW_SIGN_UP
    user: "472" # To be checked
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      -  grafana_storage:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards:/var/lib/grafana/dashboards

volumes:
  prometheus_data: {}
  grafana_storage: {}
