apiVersion: 1

datasources:
  - name: Taraxa node monitor - prometheus
    uid: tmn_prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    jsonData:
      tlsAuth: false
      tlsAuthWithCACert: false   
