{
 "title": "Taraxa Mainnet Node (new)",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({job=\"taraxa_node\"},instance)"
    }
   },
   {
    "name": "pbft_period_mainnet",
    "label": "Current mainnet PBFT period",
    "query": {
     "query": "query_result(pbft_period{instance=\"taraxa-rpc-mainnet\"})"
    }
   },
   {
    "name": "node_address",
    "label": "Node address",
    "query": {
     "query": "label_values({job=\"json_node_stats\"},node_address)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Disk usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_fs_usage_bytes{instance=\"$instance\", device=~\"/dev/m.*\", id=\"/\"}/container_fs_limit_bytes{instance=\"$instance\", device=~\"/dev/m.*\", id=\"/\"}*100",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_fs_usage_bytes{instance=\"$instance\", device=~\"/dev/m.*\", id=\"/\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{instance=\"$instance\", image != \"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory used per container",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{instance=\"$instance\", image != \"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{instance=\"$instance\",image!=\"\"}[5m]) * 100)",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "CPU usage per container",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{instance=\"$instance\", image != \"\"}[5m]) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network in/out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "-irate(container_network_transmit_bytes_total{instance=\"$instance\", name=~\"reverse_proxy|mainnet-node-1\", image!=\"\"}[$__rate_interval])",
     "legendFormat": "{{name}} tx"
    },
    {
     "expr": "irate(container_network_receive_bytes_total{instance=\"$instance\", name=~\"reverse_proxy|mainnet-node-1\", image!=\"\"}[$__rate_interval])",
     "legendFormat": "{{name}} rx"
    }
   ]
  },
  { "title": "Node status (RPC)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Trx per sec",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(rpc_node_status_trx_count{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sync status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_node_status_pbft_size{instance=\"$instance\"}/$pbft_period_mainnet*100",
     "legendFormat": "instance"
    }
   ]
  },
  {
   "title": "Instance version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(rpc_node_taraxa_get_version_result{instance=\"$instance\"}) by (version, instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PBFT period",
   "type": "timeseries",
   "description": "Discovered and connected peers",
   "gridPos": { "h": 8, "w": 12, "x": 10, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pbft_period{instance=~\"$instance|taraxa-rpc-mainnet\", data_source=\"node_rpc\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Peer count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_node_status_peer_count{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_node_status_node_count{instance=\"$instance\"}",
     "legendFormat": "node"
    }
   ]
  },
  {
   "title": "rpc.mainnet.taraxa.io",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(rpc_node_taraxa_get_version_result{instance=\"taraxa-rpc-mainnet\"}) by (version, instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Indexer stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Block produced",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "indexer_stats_dags_count{node_address=\"$node_address\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "indexer_stats_pbft_count{node_address=\"$node_address\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Last PBFT block produced",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indexer_stats_last_pbft_timestamp{node_address=\"$node_address\"}*1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "indexer_stats_last_pbft_timestamp{node_address=\"$node_address\"}*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last DAG block produced",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "indexer_stats_last_dag_timestamp{node_address=\"$node_address\"}*1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "indexer_stats_last_dag_timestamp{node_address=\"$node_address\"}*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node (default prometheus metrics)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 }
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "description": "Discovered and connected peers",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "network_discovered_peers_count{instance=\"$instance\"}",
     "legendFormat": "Discovered Peers"
    },
    {
     "expr": "network_peers_count{instance=\"$instance\"}",
     "legendFormat": "Connected Peers"
    }
   ]
  },
  {
   "title": "Votes",
   "type": "timeseries",
   "description": "Eligible votes count increases with the amount of TARA staked on this node. ",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
   "targets": [
    {
     "expr": "pbft_votes_count{instance=\"$instance\"}",
     "legendFormat": "Votes Count"
    }
   ]
  },
  {
   "title": "Syncing",
   "type": "timeseries",
   "description": "How many seconds the node is actively syncing and not participating in the consensus",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "network_syncing_duration_sec{instance=\"$instance\"}",
     "legendFormat": "Sync State"
    }
   ]
  },
  { "title": "Taraxa Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Block Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "pbft_block_transactions_count{instance=\"$instance\"}",
     "legendFormat": "Count"
    },
    {
     "expr": "rate(pbft_block_transactions_count{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "tps"
    }
   ]
  },
  {
   "title": "Queue Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
   "targets": [
    {
     "expr": "transaction_queue_transactions_count{instance=\"$instance\"}",
     "legendFormat": "Queue Count"
    },
    {
     "expr": "transaction_queue_gas_price{instance=\"$instance\"}",
     "legendFormat": "Gas"
    }
   ]
  },
  {
   "title": "PBFT",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pbft_period{instance=\"$instance\"}",
     "legendFormat": "PBFT Period"
    },
    {
     "expr": "pbft_block_number{instance=\"$instance\"}",
     "legendFormat": "PBFT Block Number"
    },
    {
     "expr": "pbft_round{instance=\"$instance\"}",
     "legendFormat": "PBFT Round"
    },
    {
     "expr": "pbft_step{instance=\"$instance\"}",
     "legendFormat": "PBFT Step"
    }
   ]
  }
 ]
}